service: splattim-lambda

custom: ${file(./env.${opt:stage, 'dev'}.yml)}

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - insomnia/**/*
  include:
    - src/handler.ts
    - src/**/*

functions:
  splatTimGoogle:
    handler: src/integrations/google/handler.splatTim
    events:
      - http:
          path: splattimgoogle
          method: post
  splatTimAmazon:
    handler: src/integrations/amazon/handler.splatTim
    events:
      - alexaSkill
    environment:
      ALEXA_APP_ID: ${self:custom.ALEXA_APP_ID}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

