service: splattim-lambda

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - insomnia/**/*
  include:
    - src/handler.ts
    - src/**/*

functions:
  splatTimGoogle:
    handler: src/integrations/google/handler.splatTim
    events:
      - http:
          path: splattimgoogle
          method: post
  splatTimAmazon:
    handler: src/integrations/amazon/handler.splatTim
    events:
      - http:
          path: splattimamazon
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline

